import type { Member } from "@/types/member"

export async function fetchMockMembers(): Promise<Member[]> {
  return [
    {
      id: 1,
      userName: "강경원",
      nickName: "theo",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 2,
      userName: "권혜진",
      nickName: "sunset",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 3,
      userName: "이은지",
      nickName: "ebbll",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 4,
      userName: "이재엽",
      nickName: "jaeyeop",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 5,
      userName: "박성진",
      nickName: "bang",
      role: "ADMIN",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 6,
      userName: "강영현",
      nickName: "ke",
      role: "USER",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 7,
      userName: "김원필",
      nickName: "pill",
      role: "USER",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 8,
      userName: "윤도운",
      nickName: "don",
      role: "USER",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 9,
      userName: "김희주",
      nickName: "hj",
      role: "USER",
      createDate: new Date("2013-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 10,
      userName: "김현주",
      nickName: "hj",
      role: "USER",
      createDate: new Date("2013-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 11,
      userName: "박수아",
      nickName: "ssooa",
      role: "USER",
      createDate: new Date("2024-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
  ]
}
