import type { Member } from "@/schemas/members"

export async function fetchMockMembers(): Promise<Member[]> {
  return [
    {
      id: 1,
      username: "강경원",
      nickname: "theo",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 2,
      username: "권혜진",
      nickname: "sunset",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 3,
      username: "이은지",
      nickname: "ebbll",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 4,
      username: "이재엽",
      nickname: "jaeyeop",
      role: "ADMIN",
      createDate: new Date("2025-03-06"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 5,
      username: "박성진",
      nickname: "bang",
      role: "ADMIN",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 6,
      username: "강영현",
      nickname: "ke",
      role: "USER",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 7,
      username: "김원필",
      nickname: "pill",
      role: "USER",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 8,
      username: "윤도운",
      nickname: "don",
      role: "USER",
      createDate: new Date("2015-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 9,
      username: "김희주",
      nickname: "hj",
      role: "USER",
      createDate: new Date("2013-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 10,
      username: "김현주",
      nickname: "hj",
      role: "USER",
      createDate: new Date("2013-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
    {
      id: 11,
      username: "박수아",
      nickname: "ssooa",
      role: "USER",
      createDate: new Date("2024-09-07"),
      modifiedDate: new Date("2025-05-07"),
    },
  ]
}
